test_that("realpath", {
    unlink(c("AAA", "BBB"), recursive = TRUE)
    dir.create("AAA")
    file.create("BBB")
    path <- c("aaa" = "AAA", "bbb" = "BBB")
    out <- realpath(path)
    expect_named(out)
    expect_identical(basename(out), unname(path))
    unlink(path, recursive = TRUE)
    expect_error(realpath(path))
})
