#!/usr/bin/env Rscript

acidbase::parseArgs(
    requiredFlags = c("aaa", "bbb"),
    optionalFlags = c("ccc", "ddd", "yyy"),
    requiredArgs = c("eee", "fff"),
    optionalArgs = c("ggg", "hhh", "zzz"),
    positionalArgs = TRUE
)
